//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RehabilityApplication.CoreLib {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LanguageRU {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LanguageRU() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RehabilityApplication.CoreLib.LanguageRU", typeof(LanguageRU).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавить запись.
        /// </summary>
        internal static string bAddRecord {
            get {
                return ResourceManager.GetString("bAddRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Очистить клиентов.
        /// </summary>
        internal static string bClearClients {
            get {
                return ResourceManager.GetString("bClearClients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Создать БД.
        /// </summary>
        internal static string bCreateDatabase {
            get {
                return ResourceManager.GetString("bCreateDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Создать папку.
        /// </summary>
        internal static string bCreateFolderOnYandexDisk {
            get {
                return ResourceManager.GetString("bCreateFolderOnYandexDisk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Создать таблицу.
        /// </summary>
        internal static string bCreateTable {
            get {
                return ResourceManager.GetString("bCreateTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Удалить запись.
        /// </summary>
        internal static string bDeleteRecord {
            get {
                return ResourceManager.GetString("bDeleteRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Иван, твой месседж.
        /// </summary>
        internal static string bIvanOkMessage {
            get {
                return ResourceManager.GetString("bIvanOkMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вопрос Ивана.
        /// </summary>
        internal static string bIvanQuestion {
            get {
                return ResourceManager.GetString("bIvanQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сопоставление.
        /// </summary>
        internal static string bMapping {
            get {
                return ResourceManager.GetString("bMapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сохранить БД на сервер.
        /// </summary>
        internal static string bSaveDatabaseInYandexDisk {
            get {
                return ResourceManager.GetString("bSaveDatabaseInYandexDisk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Показать записи.
        /// </summary>
        internal static string bShowDatabase {
            get {
                return ResourceManager.GetString("bShowDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Покажи сообщение.
        /// </summary>
        internal static string bShowMessage {
            get {
                return ResourceManager.GetString("bShowMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Открыть ДА/НЕТ диалоговое окно.
        /// </summary>
        internal static string bShowYesNoDialog {
            get {
                return ResourceManager.GetString("bShowYesNoDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Синхронизация.
        /// </summary>
        internal static string bSync {
            get {
                return ResourceManager.GetString("bSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выход из программы.
        /// </summary>
        internal static string btnExitApplication {
            get {
                return ResourceManager.GetString("btnExitApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сгенерировать документацию.
        /// </summary>
        internal static string btnGenerateDocuments {
            get {
                return ResourceManager.GetString("btnGenerateDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Открыть окно открытия файла.
        /// </summary>
        internal static string btnOpenFileDialog {
            get {
                return ResourceManager.GetString("btnOpenFileDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Показать сплэш-скрин.
        /// </summary>
        internal static string btnShowSplashScreen {
            get {
                return ResourceManager.GetString("btnShowSplashScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Василий, твой месседж.
        /// </summary>
        internal static string bVasiliyOkMessage {
            get {
                return ResourceManager.GetString("bVasiliyOkMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вопрос Василия.
        /// </summary>
        internal static string bVasyaQuestion {
            get {
                return ResourceManager.GetString("bVasyaQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Звонки.
        /// </summary>
        internal static string dpCalls {
            get {
                return ResourceManager.GetString("dpCalls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Клиенты.
        /// </summary>
        internal static string dpClients {
            get {
                return ResourceManager.GetString("dpClients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Паспорт клиента.
        /// </summary>
        internal static string dpPassports {
            get {
                return ResourceManager.GetString("dpPassports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Продукт отгружаемый клиенту.
        /// </summary>
        internal static string dpProductsInClient {
            get {
                return ResourceManager.GetString("dpProductsInClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Действия контрактов.
        /// </summary>
        internal static string groupContractActions {
            get {
                return ResourceManager.GetString("groupContractActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на БД.
        /// </summary>
        internal static string groupDatabase {
            get {
                return ResourceManager.GetString("groupDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Обработки документов.
        /// </summary>
        internal static string groupDocumentHandles {
            get {
                return ResourceManager.GetString("groupDocumentHandles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Из файла Excel.
        /// </summary>
        internal static string groupFromExcelFile {
            get {
                return ResourceManager.GetString("groupFromExcelFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на SQLite обработка.
        /// </summary>
        internal static string groupSQLite {
            get {
                return ResourceManager.GetString("groupSQLite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Яндекс.
        /// </summary>
        internal static string groupYandex {
            get {
                return ResourceManager.GetString("groupYandex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Учёт средств реабилитации 2023.
        /// </summary>
        internal static string MainForm {
            get {
                return ResourceManager.GetString("MainForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Контракты.
        /// </summary>
        internal static string pageContracts {
            get {
                return ResourceManager.GetString("pageContracts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на БД.
        /// </summary>
        internal static string pageDatabase {
            get {
                return ResourceManager.GetString("pageDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Документы.
        /// </summary>
        internal static string pageDocuments {
            get {
                return ResourceManager.GetString("pageDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Исходные данные.
        /// </summary>
        internal static string pageSourceData {
            get {
                return ResourceManager.GetString("pageSourceData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на SQLite менеджер.
        /// </summary>
        internal static string pageSQLite {
            get {
                return ResourceManager.GetString("pageSQLite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Яндекс диск.
        /// </summary>
        internal static string pageYandexDisk {
            get {
                return ResourceManager.GetString("pageYandexDisk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Справка.
        /// </summary>
        internal static string tabHelp {
            get {
                return ResourceManager.GetString("tabHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Уведомления.
        /// </summary>
        internal static string tabNotifies {
            get {
                return ResourceManager.GetString("tabNotifies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Настройки.
        /// </summary>
        internal static string tabSettings {
            get {
                return ResourceManager.GetString("tabSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Родительский ID.
        /// </summary>
        internal static string TL_ClientId {
            get {
                return ResourceManager.GetString("TL_ClientId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Коментарий.
        /// </summary>
        internal static string TL_Comment {
            get {
                return ResourceManager.GetString("TL_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Количество.
        /// </summary>
        internal static string TL_Count {
            get {
                return ResourceManager.GetString("TL_Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отчество.
        /// </summary>
        internal static string TL_Daddyname {
            get {
                return ResourceManager.GetString("TL_Daddyname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дата.
        /// </summary>
        internal static string TL_Date {
            get {
                return ResourceManager.GetString("TL_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Департамент.
        /// </summary>
        internal static string TL_Department {
            get {
                return ResourceManager.GetString("TL_Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Департамент ID.
        /// </summary>
        internal static string TL_DepartmentId {
            get {
                return ResourceManager.GetString("TL_DepartmentId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Номер направления.
        /// </summary>
        internal static string TL_DirectionNumber {
            get {
                return ResourceManager.GetString("TL_DirectionNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ф.И.О..
        /// </summary>
        internal static string TL_FIO {
            get {
                return ResourceManager.GetString("TL_FIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Gender.
        /// </summary>
        internal static string TL_Gender {
            get {
                return ResourceManager.GetString("TL_Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Идентификатор.
        /// </summary>
        internal static string TL_Id {
            get {
                return ResourceManager.GetString("TL_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выдан?.
        /// </summary>
        internal static string TL_IsGived {
            get {
                return ResourceManager.GetString("TL_IsGived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выделен?.
        /// </summary>
        internal static string TL_IsSelected {
            get {
                return ResourceManager.GetString("TL_IsSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Имя.
        /// </summary>
        internal static string TL_Name {
            get {
                return ResourceManager.GetString("TL_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Номер.
        /// </summary>
        internal static string TL_Number {
            get {
                return ResourceManager.GetString("TL_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Место рождения.
        /// </summary>
        internal static string TL_PlaceFrom {
            get {
                return ResourceManager.GetString("TL_PlaceFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Адрес Регистрации.
        /// </summary>
        internal static string TL_RegistrationAddress {
            get {
                return ResourceManager.GetString("TL_RegistrationAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Серия.
        /// </summary>
        internal static string TL_Serial {
            get {
                return ResourceManager.GetString("TL_Serial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на СНИЛС.
        /// </summary>
        internal static string TL_Snils {
            get {
                return ResourceManager.GetString("TL_Snils", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Фамилия.
        /// </summary>
        internal static string TL_Surname {
            get {
                return ResourceManager.GetString("TL_Surname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Телефон.
        /// </summary>
        internal static string TL_Telephone {
            get {
                return ResourceManager.GetString("TL_Telephone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Заголовок.
        /// </summary>
        internal static string TL_Title {
            get {
                return ResourceManager.GetString("TL_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сохранять как изменение.
        /// </summary>
        internal static string tsIsChanges {
            get {
                return ResourceManager.GetString("tsIsChanges", resourceCulture);
            }
        }
    }
}
